### ISSUE TITLE
What paper is this based on?

### ISSUE THREAD

**Issue by angelchi56** [aoso3/Real-Time-Abnormal-Events-Detection-and-Tracking-in-Surveillance-System#1]
Hello,
I was wondering if there is a specific paper(s) to this implementation?

Thank you.

**Comment by aoso3** [comment]
Hi,

Here are the main papers i used for this implementation:
[https://ieeexplore.ieee.org/document/7024902?section=abstract](https://ieeexplore.ieee.org/document/7024902?section=abstract) 
[https://www.researchgate.net/publication/221362278_Anomaly_Detection_in_Crowded_Scenes](https://www.researchgate.net/publication/221362278_Anomaly_Detection_in_Crowded_Scenes)
[https://www.researchgate.net/publication/220278263_Motion-based_unusual_event_detection_in_human_crowds](https://www.researchgate.net/publication/220278263_Motion-based_unusual_event_detection_in_human_crowds)
