### ISSUE TITLE
I can't add reference Telerik

### ISSUE THREAD

**Issue by maacofficial** [aoso3/Real-Time-Abnormal-Events-Detection-and-Tracking-in-Surveillance-System#2]
I added telerik reference but Telerik is not working.

**Comment by maacofficial** [comment]
can you share without telerik or you can share telerik dll with me?

**Comment by aoso3** [comment]
This project is built using Telerik library. you have to install Telerik (and other libraries mentioned in description to be able to run it).
You can install Telerik UI for WinForms from this link:
[https://www.telerik.com/products/winforms.aspx](url)

**Comment by maacofficial** [comment]
Ok! I know telerik and how to install. i can see it in references tab but it is not working in code page. When i create new blank project, it is telerik.wincontrols is working. But in your project not working.

**Comment by maacofficial** [comment]
Also can i convert telerik controls to default win controls?

**Comment by maacofficial** [comment]
Is there another way without telerik?
